### PR TITLE
fix: make event_assert crate handle multiple events in sequence

### LINKED ISSUE #123: 🐞 [Bug]: Event Assertion create only handles the first error of a kind
### What happened?

Take a look at these lines: https://github.com/OpenZeppelin/stellar-contracts/blob/main/packages/tokens/non-fungible/src/test.rs#L444

I've tested the `minting` and `counter` part, and `tokens_id`s are indeed `0` and `1`. However, although there are 2 mint events, the `event_assert` crate only deals with the first `mint` event every time (due to `find()` logic used inside of `event_assert` crate). 

### Expected behavior

We should somehow fix this, and allow `event_assert` crate to parse the next event of the same kind for each call. 

The most basic approach would be, deleting the parsed event from the queue. If the actual `events` queue is not be touched, we should:
1. clone the events for `event_assert` crate
2. delete the parsed event from the cloned list

### PR DESCRIPTION
**Pull request by YanVictorSN**
Fixes #123 

This PR changes how the `find_event_by_symbol` from `EventAssertion` handles multiple events in sequence. To achieve this, we introduced a `HashSet` called `processed_events` to keep track of the indices of the events that have already been read.

#### PR Checklist

- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ozgunozerk** [comment]
Very straight forward, and works! Love it <3

File: packages/tokens/non-fungible/src/test.rs [hunk 1]
```diff
@@ -437,7 +437,7 @@ fn test_counter_works() {
         let token_id1 = Base::sequential_mint(&e, &owner);
         let _token_id2 = Base::sequential_mint(&e, &owner);
```
Comment (ozgunozerk) [inline packages/tokens/non-fungible/src/test.rs:438]: @YanVictorSN can you also fix this and uncomment the lines beneath here? If this one is working as well, I'll approve and we can proceed with the merge

**Review by ozgunozerk — CHANGES_REQUESTED** [review]

File: packages/tokens/non-fungible/src/test.rs (hunk 1 above)
Comment (YanVictorSN) [reply packages/tokens/non-fungible/src/test.rs:438]: Sure. I'll dive into that.

Comment (YanVictorSN) [reply packages/tokens/non-fungible/src/test.rs]: @ozgunozerk Just did! But can't run the workflow, it's something with the `cargo-llvm-cov`

Comment (ozgunozerk) [reply packages/tokens/non-fungible/src/test.rs]: @YanVictorSN yes this bug is not related to your changes. Seems like our sccache needs to be updated. Opened a PR for that, should unblock you soon

**Review by ozgunozerk — APPROVED** [review]
