### PR TITLE
Fixed point error handling

### LINKED ISSUE #579: Consistent Error Handling in fixed point math
We sometimes wrap the underlying errors with our custom errors in non-checked functions, for example: `DivisionByZero`, but these are non-checked functions, and they are expected to panic. Duplicating the underlying library's errors (soroban sdk or standard rust) in our smart contract library is superfluous. 

We should refactor the fixed point math library w.r.t this.

### PR DESCRIPTION
**Pull request by ozgunozerk**
Fixes #579 and #578 

#### PR Checklist

- [x] Tests
- [x] Documentation

## Release Notes

* **Refactor**
  * Reorganized fixed-point arithmetic utilities for improved clarity and explicit rounding control. Replaced trait-based methods with dedicated free functions for multiplication and division operations.
  * Updated internal math calculations across vault operations to use rounding-aware variants, ensuring more predictable and consistent behavior in fixed-point arithmetic operations.

### CODE REVIEW

File: packages/contract-utils/src/math/i128_fixed_point.rs [hunk 1]
```diff
@@ -50,227 +63,238 @@ pub fn mul_div_i128(e: &Env, x: i128, y: i128, denominator: i128, rounding: Roun
...
-                // scale to i256 and retry
-                let x_i256 = &I256::from_i128(e, *self);
-                let y_i256 = &I256::from_i128(e, *y);
-                let z_i256 = &I256::from_i128(e, *denominator);
+/// Calculates floor(x * y / denominator) with automatic scaling to I256
+/// when necessary.
+///
+/// # Arguments
+///
+/// * `env` - Access to the Soroban environment.
```
Comment (brozorec) [inline packages/contract-utils/src/math/i128_fixed_point.rs]:
```suggestion
/// * `e` - Access to the Soroban environment.
```

File: packages/contract-utils/src/math/i128_fixed_point.rs [hunk 2]
```diff
@@ -50,227 +63,238 @@ pub fn mul_div_i128(e: &Env, x: i128, y: i128, denominator: i128, rounding: Roun
...
+/// Performs ceil(r / z)
+fn div_ceil(r: i128, z: i128) -> i128 {
+    if (r <= 0 && z > 0) || (r >= 0 && z < 0) {
+        // ceiling is taken by default for a negative or zero result
+        r / z
+    } else {
+        // floor taken by default for a positive result
+        let remainder = r.rem_euclid(z);
+
+        // check for div overflow (i128::MIN / -1)
```
Comment (brozorec) [inline packages/contract-utils/src/math/i128_fixed_point.rs]: Is this comment correct?

File: packages/contract-utils/src/math/i256_fixed_point.rs [hunk 3]
```diff
@@ -4,241 +4,234 @@
...
     }
 }
 
-/// Checked version of [`muldiv`].
+/// Checked version of [`mul_div_with_rounding_i256`].
 ///
-/// Calculates `x * y / denominator` with full precision, returning `None`
-/// instead of panicking on error.
+/// Calculates `x * y / denominator`, returning `None` on division by zero or
+/// overflow instead of panicking.
```
Comment (brozorec) [inline packages/contract-utils/src/math/i256_fixed_point.rs]: `x.mul(y)` can still panic
